### ISSUE TITLE
Make your action Verified

### ISSUE THREAD

**Issue by markphip** [devcontainers/action#118]
I am not sure what is required but it would be nice if your actions had the **Verified** flag in the Marketplace. Enterprises and Organizations can limit the Allowed Actions to only those that are Verified.

**Comment by samruddhikhandale** [comment]
@joshspicer Could you help apply for verification? Doc --> https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by joshspicer** [comment]
That link seems to be for oauth apps only - I've messaged the actions team to see what they can do for us :)

**Comment by joshspicer** [comment]
Verified!

https://github.com/marketplace/actions/dev-container-publish

Thanks for the nudge @markphip
