### ISSUE TITLE
README should add info on extensions installed by default

### ISSUE THREAD

**Issue by alefteris** [devcontainers/action#139]
The Terraform feature in its title, description and README seems that it has nothing specific to a provider but it installs Azure specific vscode extensions. The extensions installed with the feature are the "Azure Terraform" and "Azure Account" extensions.

As far as I can see, it's not possible to control the installation of extensions and settings from a feature, so I'm stuck with them if I would like to use the feature to install the rest of the terraform cli tools (the installation of the individual cli tools can be controlled from the feature options).

I propose to make the terraform feature provider neutral by removing those extensions from the feature. A separate feature can be created for installing Azure specific extensions for Terraform.

**Comment by samruddhikhandale** [comment]
> But I still think that features should mention, at least in their READMEs, what extensions they are adding by default.

I agree! Moved this enhancement request to the right repo.

**Comment by samruddhikhandale** [comment]
Opened https://github.com/devcontainers/action/pull/172

**Comment by samruddhikhandale** [comment]
Released changes in the latest `action`.
