### ISSUE TITLE
@joshspicer [https://apps.apple.com/tw/app/%E6%98%9F%E5%9F%8Eonline-%E6%98%9F%E5%B9%A3%E7%88%AD%E9%9C%B8%E6%88%B0%E6%90%B6%E5%84%84%

### ISSUE THREAD

**Issue by Gesisfm** [devcontainers/action#144]
@joshspicer [https://apps.apple.com/tw/app/%E6%98%9F%E5%9F%8Eonline-%E6%98%9F%E5%B9%A3%E7%88%AD%E9%9C%B8%E6%88%B0%E6%90%B6%E5%84%84%E8%90%AC%E5%BD%A9%E9%87%91/id919043762](htt`https://www.bing.com/fd/ls/GLinkPing.aspx?IG=60B0D2239CD5446EA09B81C274DBF66A&&ID=SERP,5177.1&SUIH=4ieSXRL9zCbYVzCgp9nqpA&redir=aHR0cHM6Ly9hcHBzLmFwcGxlLmN`)

_Originally posted by @Gesisfm in https://github.com/devcontainers/spec/issues/196#issuecomment-1418263045_

**Comment by bamurtaugh** [comment]
Hi there, it seems this may have been opened by mistake. If you have a feature request or bug related to this repo, please let us know. Thanks!

**Comment by Gesisfm** [comment]
#143 
https://www.bing.com/fd/ls/GLinkPing.aspx? IG=60B0D2239CD5446EA09B81C274DBF66A&&ID=SERP,5177.1&SUIH=4ieSXRL9zCbYVzCgp9nqpA&redir=aHR0cHM6Ly9hcHBzLmFwcGxlLmNvb@Gesisf
