### ISSUE TITLE
Feature Request: Publish Image

### ISSUE THREAD

**Issue by CodeMan99** [devcontainers/action#200]
## Note

Not sure if this conversation belongs here.

## Feature Request

Add a github action to publish docker images created by `devcontainer build`.

### Where

By default, publish to `ghcr.io/<username>/<repo>/devcontainer` or similar.

### Why

This seems like an easy win to share builds in large teams.

### Up Next

Add a [cli](https://github.com/devcontainers/cli) flag that will automatically pull the ghcr.io image.

```shell
$ devcontainer build --pull                       # will look for the latest image in the default ghcr.io location
$ devcontainer build --pull mcr.microsoft.com/devcontainers/action:latest  # or a specified repository

**Comment by samruddhikhandale** [comment]
Hi 👋 

Have you looked at the https://github.com/devcontainers/ci repo? We already have `devcontainers/ci@v0.3` which can be used for the same purpose.

Feel free to open issue in https://github.com/devcontainers/ci/issues if you have any other questions.

**Comment by CodeMan99** [comment]
I've glanced over the _devcontainers/ci_ repository many times, but never made the connection.

I'm going to think about the documentation a little bit to see if I can make this particular idea more eye catching.
