### ISSUE TITLE
Feature caching with docker-compose

### ISSUE THREAD

**Issue by cjam** [devcontainers/action#218]
I have a project with a docker-compose based devcontainer setup.  
I have a dockerfile for my devcontainer image as well as a number of features defined in the `devcontainer.json`.

I can't figure out how to get the caching to work for our github actions.  It seems that everytime I use this devcontainer within github actions it spends ~5 minutes rebuilding the container and all of it's features.

Is there an example of caching setup properly with a docker-compose setup?

**Comment by samruddhikhandale** [comment]
Hi 👋 

Have you looked at https://github.com/devcontainers/ci? Let us know if that helps, else happy to chat about other possible solutions. Thanks!

**Comment by cjam** [comment]
ah thanks @samruddhikhandale I think I put this issue into the wrong repo.  I'll close this one and open one in that repo, thanks.
