### ISSUE TITLE
[publish-features] releases dev container (non-devcontainer-feature) from root of repo

### ISSUE THREAD

**Issue by snebjorn** [devcontainers/action#81]
The setup given by the [feature-template](https://github.com/devcontainers/feature-template/blob/main/.github/workflows/release.yaml#L16) correctly releases features pointed to by `base-path-to-features: "./src"`.

However it also releases the [.devcontainer.json located at the root](https://github.com/devcontainers/feature-template/blob/main/.devcontainer.json) of the repo which is not located in `./src`. It's not even a **devcontainer-feature**.

See this repo for details https://github.com/snebjorn/devcontainer-feature

Notice it released 2 packages
![image](https://user-images.githubusercontent.com/1266245/196030750-38a4a872-d437-4de2-97f3-fe7642ecaee4.png)

**Comment by joshspicer** [comment]
Hey @snebjorn!  The contents of `devcontainer-feature` is metadata on all of the other Features published within the same namespace (from that repo).  We use that package [when crawling collections](https://containers.dev/collections) (and other supporting tools could do the same).

That package contains a single `devcontainer-collection.json` that we use to build the [index](https://containers.dev/features).  If you had more than one Feature in this repo, it would also show up in this array.

```
joshspicer@gh-m1 /tmp % oras pull ghcr.io/snebjorn/devcontainer-feature:latest
Downloading d862e64c12be devcontainer-collection.json
Downloaded  d862e64c12be devcontainer-collection.json
Pulled ghcr.io/snebjorn/devcontainer-feature:latest
Digest: sha256:13eeb11b16c33e78597868b2ce9a045006a9d3e9844ee6174431513302e67c91
joshspicer@gh-m1 /tmp % cat devcontainer-collection.json| jq
{
  "sourceInformation": {
    "source": "devcontainer-cli"
  },
  "features": [
    {
      "name": "Chromium",
      "id": "chromium",
      "version": "1.0.0",
      "description": "Chromium",
      "options": {},
      "containerEnv": {
        "CHROME_BIN": "/usr/bin/chromium",
        "CHROMIUM_BIN": "/usr/bin/chromium"
      },
      "capAdd": [
        "SYS_ADMIN"
      ],
      "securityOpt": []
    }
  ]
}
joshspicer@gh-m1 /tmp %
```

**Comment by snebjorn** [comment]
I see, my bad
