### ISSUE TITLE
`Example Usage` in README.md Generated Incorrectly

### ISSUE THREAD

**Issue by natescherer** [devcontainers/action#85]
Just wanted to call out that the `Example Usage` section of README.md appears to generate incorrectly when "version" isn't one of the options; it still shows "version": latest as the only option.

Here's my `devcontainer-feature.json`
https://github.com/natescherer/devcontainers-custom-features/blob/550cf03ac41f85ffbe5bd0aa7fb2d0856a026751/src/powershell-resources/devcontainer-feature.json

And here's the README.md the action generated :
https://github.com/natescherer/devcontainers-custom-features/blob/550cf03ac41f85ffbe5bd0aa7fb2d0856a026751/src/powershell-resources/README.md

**Comment by bamurtaugh** [comment]
Thanks for reporting! 

@joshspicer is this meant to be hardcoded? https://github.com/devcontainers/action/blob/13e680725131f6da8c64ed236d309b3182c87d31/src/generateDocs.ts#L11

**Comment by joshspicer** [comment]
Agreed that shouldn't happen :) Thanks for the report.
