### ISSUE TITLE
Action should immediately fail when it fails to PUT a tag

### ISSUE THREAD

**Issue by samruddhikhandale** [devcontainers/action#90]
Issue mentioned here --> https://github.com/devcontainers/spec/issues/61#issuecomment-1292804969

As the corresponding publish action showed a ✅  , the user would not realize that it failed to publish some tag. Need to fail the action as soon as CLI fails to PUT a tag. 

// cc @eitsupi

**Comment by metaskills** [comment]
I ran into this issue when I also found a possible `ERR_FR_MAX_BODY_LENGTH_EXCEEDED ` bug in the CLI here https://github.com/devcontainers/cli/issues/270

**Comment by samruddhikhandale** [comment]
@joshspicer looks like https://github.com/devcontainers/action/pull/105 should fix this issue?

**Comment by samruddhikhandale** [comment]
oh wait maybe not! The CLI still needs to be changed to return a non-zero exit code

**Comment by samruddhikhandale** [comment]
Closing as fixed with https://github.com/devcontainers/cli/pull/296
