### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by devenes** [devcontainers/action#99]
The GitHub Actions workflow gives the following error while running the action:

> Node.js 12 actions are deprecated. For more information see: github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12.

**Comment by devenes** [comment]
Merged 🚀 #100

**Comment by samruddhikhandale** [comment]
Hey @joshspicer Can you help create a release for this `action` with the https://github.com/devcontainers/action/pull/100 changes? Thanks!
